# Generated by Django 4.1.6 on 2023-02-15 23:37

from django.db import migrations

scale_data = [
    (1, "Starving", "Starving, no energy, very weak"),
    (2, "Very_hungry", "Very hungry, low energy, weak and dizzy"),
    (3, "Uncomfortably_hungry", "Uncomfortably hungry, distracted, irritable"),
    (4, "Hungry", "Hungry, stomach growling"),
    (5, "Good", "Starting to feel hungry"),
    (6, "Satisfied", "Satisfied, but could eat a little more"),
    (7, "Full", "Full but not uncomfortable"),
    (8, "Overfull", "Overfull, somewhat uncomfortable"),
    (9, "Stuffed", "Stuffed, very uncomfortable"),
    (10, "Extremely_stuffed", "Extremely stuffed, nauseous")
]


def create_scale(apps, schema_editor):
    """Create scale."""
    scale = apps.get_model('web', 'Scale')
    scale_obj = scale.objects.create(
        scale_name="Hunger_Satiety_Scale",
        scale_full_name="Hunger-Satiety Scale",
        min_amount=1,
        max_amount=10,
        step=1,
        better_amount=5,
        default=True
    )
    feeling = apps.get_model('web', 'Feeling')
    for item in scale_data:
        feeling.objects.create(
            scale=scale_obj,
            feeling_name=item[1],
            feeling_full_name=item[2],
            amount=item[0]
        )


def remove_scale(apps, schema_editor):
    """Remove scales."""
    scale = apps.get_model('web', 'Scale')
    feeling = apps.get_model('web', 'Feeling')
    scale.objects.all().delete()
    feeling.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=create_scale, reverse_code=remove_scale),
    ]
